//
//  main.c
//
//  Created by Jasmine Talukder on 24/12/2014.
//  Copyright (c) 2014 Jasmine Enterprise. All rights reserved.

/* PROBLEM 1:
 If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
 Find the sum of all the multiples of 3 or 5 below 1000.
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#define FOUR_MILLION 4000000

int multiple(){
    int result = 0;
    for(int i = 0; i < 1000; i++){
        if((i % 3 == 0) || (i % 5 == 0)){
            result += i;
        }
    }
    return result;
}
/*PROBLEM 2:
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

long sum_even_fib(){
    long f = 1, s = 2, next = s,r = 0;
    while(next < FOUR_MILLION){
        if(next % 2 == 0){
            r += next;
        }
        next = f+s;
        f = s;
        s = next;
    }
    return r;
}
/*PROBLEM 3:
 The prime factors of 13195 are 5, 7, 13 and 29.
 What is the largest prime factor of the number 600851475143
 */
long primeFactor(long number){
    long div =2;
    while(number !=0){
        if(number%div!=0)
            div = div + 1;
        else {
            number = number / div;
            if(number==1)
                break;
        }
    }
    return div;
}
/*Reverse function*/
void strrev(char *b){
    char temp;
    int x = 0;
    int y = (int)strlen(b) - 1;
    while (x < y) {
        temp = b[x];
        b[x] = b[y];
        b[y] = temp;
        x++;
        y--;
    }
}
/*PROBLEM 4
 A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
 Find the largest palindrome made from the product of two 3-digit numbers.
 */
long largetPalindrome(){
    long r =0, prod;
    //char *ptr;
    char a[30], b[30];
   // long t=0;
    for(int i = 999; i >= 100; i--){
        for(int j  = 999; j >= 100; j--){
            prod = (i * j);
            sprintf(a, "%ld", prod);     //int convert to char
            strcpy(b, a);
            strrev(b);
           // t = strtol(a,&ptr,10);    //char convert to int
            if((strcmp(a,b)==0)&&(prod>r>0)){
                r = prod;
            }
        }
    }
    return r;
}
/*PROBLEM 5
 What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?
 */
int divisible(){
    int r = 0,j;
    for(int i = 1; 1;i++){
        for(j = 1; j <= 20; j++){
            if(i%j!=0){
                break;
            }
        }
        if(j>20){
            r = i;
            break;
        }
    }
    return r;
}
int main(int argc, const char * argv[]) {
    int r = multiple();
    long even = sum_even_fib();
    long prime = primeFactor(600851475143);
    printf("The sum of all the multiples of 3 or 5 below 1000:\n%d\n", r);
    printf("The sum of the even-valued terms:\n%ld\n",even);
    printf("The largest prime factor of the number 600851475143:\n%ld\n",prime);
    long rst = largetPalindrome();
    printf("The largest palindrome made from the product of two 3-digit numbers:\n%ld\n", rst);
    int div = divisible();
    printf("The smallest positive number that is evenly divisible by all of the numbers from 1 to 20:\n%d",div);
    return 0;
}
